### ISSUE TITLE
Broken Link in Assignment: GitHub, Jupyter, Python, Numpy

### ISSUE THREAD

**Issue by Camgur** [QC-Edu/IntroQM#4]
Hi @PaulWAyers ,

The link in part one: 

Go through the course’s [introduction to computer programming and computer programming tools](https://qchem.qc-edu.org/jupyter.ipynb.html).

appears to be broken. The resulting page has no content, and the title is just the location of the Jupyter.ipynb notebook.

I wasn't sure how to submit a broken link as a pull request, so hopefully this is okay.

![Blank Page](https://github.com/QC-Edu/IntroQM/assets/156104897/2482c766-924b-41bc-aaf0-60a241932c5b)

**Comment by RichRick1** [comment]
@Camgur thanks for the catch, I've fixed it

**Comment by RichRick1** [comment]
Fixed the broken link
